services:
  desktop:
    build: .
    ports:
      - "6901:6901"
    shm_size: '2g' # Increase shared memory size for applications like Chrome
    volumes:
      - homedir:/home/dev

volumes:
  homedir:
